version: '3.1'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./data:/var/lib/mongodb
